---

- name: Stop all the test instances
  hosts: localhost
  connection: local
  become: false
  vars:
    state: 'stopped'
  vars_files:
    - '{{ playbook_dir }}/../../config/systems-{{ env }}.yml'
  roles:
    - setup-environment
